#!/usr/bin/python3



import os
import sys
from pyaxmlparser import APK



os.system('clear')



application = sys.argv[1]
apkinput = APK(application)
package = apkinput.package
vname = apkinput.version_name
vcode = apkinput.version_code



appnfile = '{}.{}.apk'.format(package, vcode)



print(application)
print(appnfile)



os.system('clear')



os.rename('{}'.format(application), '{}'.format(appnfile))
os.system('ls')
