#!/usr/bin/python3

from os import system
from time import sleep

list_of_commands = [
    'adb reboot bootloader',
    'fastboot reboot bootloader',
    'fastboot reboot fastboot',
    'fastboot --set-active=a',
    'fastboot flash --disable-verity --disable-verification vbmeta vbmeta.img',
    'fastboot flash --disable-verity --disable-verification boot boot.img',
    'fastboot flash dtbo dtbo.img',
    'fastboot flash vendor vendor.img',
    'fastboot delete-logical-partition product_a',
    'fastboot erase system',
    'fastboot flash system system.img',
    'fastboot -w',
]

total_step = len(list_of_commands)

def show_progress(current_step, total_step, executing_command):
    msg_base = 'Current progress:'
    percentage = round((current_step * 100) / total_step)

    cols = 128
    check_col = round((percentage * cols) / 100)
    check_col_char = ('▸' * check_col)

    uncheck_col = (cols - check_col)
    uncheck_col_char = (' ' * uncheck_col)

    system('clear')
    print('[{}{}] ! {}%'.format(check_col_char, uncheck_col_char, percentage))
    print('Command: {}'.format(executing_command))
    sleep(0.5)



def execute_command(command, this_step, total_step=total_step):
    show_progress(this_step, total_step, command)
    system(command)


for cmd in list_of_commands:
    index = (list.index(list_of_commands, cmd) + 1)
    execute_command(cmd, index, total_step)
